apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kirro
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - configmap.yaml
  - deployments.yaml
  - allocator-cronjob.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cheetos-gif/kirro
    newName: ghcr.io/cheetos-gif/kirro
    digest: sha256:4709711bb6145f82abbd6ca7c44353ed86388fb0eb6e778591f1d58b60a68676
