apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kirro
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - configmap.yaml
  - deployments.yaml
  - allocator-cronjob.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cheetos-gif/kirro
    newName: ghcr.io/cheetos-gif/kirro
    digest: sha256:1d54e2d262723c9ee568abe9486b59e106e7fffeb5aea9cb996d2f73e55ad6fa
