apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kirro
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - pvc.yaml
  - configmap.yaml
  - deployments.yaml
  - allocator-cronjob.yaml
  - agent-stats-sync-cronjob.yaml
  - services.yaml
  - ingress.yaml
images:
  - name: ghcr.io/cheetos-gif/kirro
    newName: ghcr.io/cheetos-gif/kirro
    digest: sha256:68de03628dbb05646fe2bbd1c93e0e84396ca8dfb4e4a87c8c6a130bb2b0ad5a
